### ISSUE TITLE
Improve persistence of IPAM data

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave-kube#27]
Currently weave-daemonset.yaml specifies an `emptyDir` volume which is deleted when the pod is deleted. Since upgrading `weave-kube` require deleting the pods, this is unsafe.

Reading http://kubernetes.io/docs/user-guide/volumes/, I don't see an obviously better choice.

**Comment by Bregor** [comment]
I think regular `hostPath` will suit this as well.
Example:

```
      volumeMounts:
        - mountPath: /weave_data
          name: data
...
  volumes:
    - name: data
      hostPath:
        path: /var/lib/weave-kube
```
